image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

before_script:
  - docker info
  - make login

build_image:
  stage: build
  script:
  - make build

test_image:
  stage: test
  script:
  - make test

push_image:
  stage: deploy
  only:
  - tags
  except:
  - /^(?!master).+@/
  script:
  - make tp