ARG RUBY_PATH=/usr/local/
ARG RUBY_VERSION=2.7.4
ARG BUNDLE_RUBYGEMS__PKG__GITHUB__COM

FROM ubuntu:20.04 AS rubybuild
ARG RUBY_PATH
ARG RUBY_VERSION
ARG BUNDLE_RUBYGEMS__PKG__GITHUB__COM

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
      git \
      curl \
      autoconf \
      bison \
      build-essential \
      libssl-dev \
      libyaml-dev \
      libreadline6-dev \
      zlib1g-dev \
      libncurses5-dev \
      libffi-dev \
      libgdbm6 \
      libgdbm-dev \
      snapd

RUN git clone git://github.com/rbenv/ruby-build.git $RUBY_PATH/plugins/ruby-build \
  && $RUBY_PATH/plugins/ruby-build/install.sh

RUN ruby-build $RUBY_VERSION $RUBY_PATH

FROM ubuntu:20.04
USER root
LABEL maintainer="open.source@ribose.com"
ARG RUBY_PATH
ARG BUNDLE_RUBYGEMS__PKG__GITHUB__COM
ENV PATH $RUBY_PATH/bin:$PATH
COPY --from=rubybuild $RUBY_PATH $RUBY_PATH

ENV DEBIAN_FRONTEND=noninteractive
ENV CONTAINER_TIMEZONE=Etc/UTC
RUN ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && \
  echo $CONTAINER_TIMEZONE > /etc/timezone

# install dependencies
RUN apt-get update && apt-get install -y \
  curl gnupg2 software-properties-common python3-pip

RUN mkdir -p /setup

COPY ./ubuntu.sh /setup/ubuntu.sh
RUN bash -c /setup/ubuntu.sh

# From https://github.com/docker-library/ruby/blob/master/
#   Dockerfile-debian.template
# don't create ".bundle" in all our apps
ENV GEM_HOME /usr/local/bundle
ENV BUNDLE_SILENCE_ROOT_WARNING=1 \
	BUNDLE_APP_CONFIG="$GEM_HOME"
ENV PATH $GEM_HOME/bin:$PATH
# adjust permissions of a few directories for running "gem install" as an arbitrary user
RUN mkdir -p "$GEM_HOME" && chmod 777 "$GEM_HOME"
# End From

# install latest bundler
RUN gem install bundler

ENV BUNDLE_RUBYGEMS__PKG__GITHUB__COM=$BUNDLE_RUBYGEMS__PKG__GITHUB__COM

# install metanorma toolchain
COPY ${METANORMA_IMAGE_NAME}/Gemfile /setup/Gemfile
# Specially build sassc due to incompatible binary metanorma/metanorma-docker#51
RUN cd /setup \
  && bundle config --local build.sassc --disable-march-tune-native \
  && bundle install --verbose

# cleanup and set base entrypoint
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# export java executable path
ENV JAVA_HOME /usr/lib/jvm/default-java
ENV PATH $PATH:$JAVA_HOME/bin
ENV RUBYOPT -rbundler/setup
ENV BUNDLE_GEMFILE /setup/Gemfile

ENV FONTIST_PATH "/config"
VOLUME /config/fonts

WORKDIR /metanorma
CMD metanorma
