ARG RUBY_PATH=/usr/local/
ARG RUBY_VERSION=2.6.5

FROM ubuntu:latest AS rubybuild
ARG RUBY_PATH
ARG RUBY_VERSION
RUN apt-get update && \
    apt-get install -y \
      git \
      curl \
      autoconf \
      bison \
      build-essential \
      libssl-dev \
      libyaml-dev \
      libreadline6-dev \
      zlib1g-dev \
      libncurses5-dev \
      libffi-dev \
      libgdbm5 \
      libgdbm-dev

RUN git clone git://github.com/rbenv/ruby-build.git $RUBY_PATH/plugins/ruby-build \
  && $RUBY_PATH/plugins/ruby-build/install.sh

RUN ruby-build $RUBY_VERSION $RUBY_PATH

FROM ubuntu:latest
USER root
MAINTAINER Open Source at Ribose <open.source@ribose.com>
ARG RUBY_PATH
ENV PATH $RUBY_PATH/bin:$PATH
COPY --from=rubybuild $RUBY_PATH $RUBY_PATH

# install dependencies
RUN apt-get update && apt-get install -y \
  curl gnupg2 software-properties-common python3-pip
RUN ./ubuntu.sh

# From https://github.com/docker-library/ruby/blob/master/
#   Dockerfile-debian.template
# don't create ".bundle" in all our apps
ENV GEM_HOME /usr/local/bundle
ENV BUNDLE_SILENCE_ROOT_WARNING=1 \
	BUNDLE_APP_CONFIG="$GEM_HOME"
ENV PATH $GEM_HOME/bin:$PATH
# adjust permissions of a few directories for running "gem install" as an arbitrary user
RUN mkdir -p "$GEM_HOME" && chmod 777 "$GEM_HOME"
# End From

# install latest bundler
RUN gem install bundler

# install metanorma toolchain
RUN mkdir -p /setup
COPY ${METANORMA_IMAGE_NAME}/Gemfile /setup/Gemfile
# Specially build sassc due to incompatible binary metanorma/metanorma-docker#51
RUN cd /setup \
  && bundle config --local build.sassc --disable-march-tune-native \
  && bundle install --verbose

# cleanup and set base entrypoint
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# export java executable path
ENV JAVA_HOME /usr/lib/jvm/default-java
ENV PATH $PATH:$JAVA_HOME/bin
ENV RUBYOPT -rbundler/setup
ENV BUNDLE_GEMFILE /setup/Gemfile

# load NVM
ENV NVM_DIR "/root/.nvm"
ENV NODE_PATH "$NVM_DIR/versions/node/v12.4.0/lib/node_modules"
ENV PATH "$PATH:$NVM_DIR/versions/node/v12.4.0/bin"

WORKDIR /metanorma
CMD metanorma
