FROM ruby:2.6-slim-buster
USER root

MAINTAINER Open Source at Ribose <open.source@ribose.com>

# install dependencies
RUN apt-get update && apt-get install -y \
  curl gnupg2 software-properties-common python3-pip snapd

RUN mkdir -p /setup

# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199#23
RUN mkdir -p /usr/share/man/man1

COPY ./ubuntu.sh /setup/ubuntu.sh
RUN bash -c /setup/ubuntu.sh

# install latest bundler
RUN gem install bundler

# install metanorma toolchain
COPY ${METANORMA_IMAGE_NAME}/Gemfile /setup/Gemfile
# Specially build sassc due to incompatible binary metanorma/metanorma-docker#51
RUN cd /setup \
  && bundle config --local build.sassc --disable-march-tune-native \
  && bundle install --verbose

# export java executable path
ENV JAVA_HOME /usr/lib/jvm/default-java
ENV PATH $PATH:$JAVA_HOME/bin
ENV RUBYOPT -rbundler/setup
ENV BUNDLE_GEMFILE /setup/Gemfile

# Workaround for rubygems/bundler#7494
# TODO: Supposed to be already fixed but why is this necessary?
ENV GEM_PATH $GEM_HOME:$GEM_HOME/ruby/$RUBY_MAJOR.0
ENV PATH $GEM_HOME/bin:$GEM_HOME/ruby/$RUBY_MAJOR.0/bin:$PATH

# cleanup and set base entrypoint
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# load NVM
ENV NVM_DIR "/root/.nvm"
ENV NODE_PATH "$NVM_DIR/versions/node/v12.4.0/lib/node_modules"
ENV PATH "$PATH:$NVM_DIR/versions/node/v12.4.0/bin"

WORKDIR /metanorma
CMD metanorma
