= Metanorma Linux Container (Ubuntu)

== Purpose

This is the cross-platform solution for Metanorma
that works on all OSes, including Windows.

Some people mentioned setting up Metanorma on macOS felt
cumbersome (well...).


== Prerequisites

All you need is install Docker as shown below.

macOS:

* *Recommended* Install using the
https://github.com/riboseinc/metanorma-macos-setup[Metanorma macOS Setup Script]
instead of this docker container
* https://www.docker.com/products/docker-desktop[Docker Desktop for Mac]

Windows:

* https://www.docker.com/products/docker-desktop[Docker Desktop for Windows (10)]
* https://docs.docker.com/toolbox/overview/[Docker Toolbox for legacy Windows]

Linux:

* https://docs.docker.com/install/linux/docker-ce/ubuntu/[Docker CE for Ubuntu]
* https://docs.docker.com/install/linux/docker-ce/centos/[Docker CE for CentOS]
* https://docs.docker.com/install/linux/docker-ce/debian/[Docker CE for Debian]


== Pulling the container

This container is published at the
https://hub.docker.com/r/ribose/metanorma/[Docker Registry] as `docker.io/ribose/metanorma` or `ribose/metanorma`,
and can be pulled with the following command:

[source,sh]
----
docker pull ribose/metanorma
----


== Usage


=== Setting document attributes for docker compilation

The `:local-cache-only:` document attribute should be set in your
document in order to take advantage of local caching of
bibliographic items fetched from the Internet.

NOTE: Normally, the Metanorma toolchain assumes that you have a global
bibliographic cache located in `~/.relaton/cache` and
`~/.iev.bib.pstore`. However, when run in a docker container,
the global cache is not shared between the host and the container.

By setting `:local-cache-only`, Metanorma will not generate a global
bibliographic cache, and will store a cache instance for each document
in the local working directory, which is shared between the host
and the container, as in:

* `./relaton/cache`; and
* `./{document-name}.iev.bib.pstore`.

The document attribute is to be set in the document header, like this:

[source,adoc]
----
= ISO 8601-2
:docnumber: 8601
:partnumber: 2
:ref-docnumber: 8601-2:2018(E)
:title-intro-en: Date and time
:title-main-en: Representations for information interchange
:title-part-en: Extensions
// ...
:local-cache-only:
----

These files can also be checked-in into version control.


=== Compiling a Metamorma document via docker

In a directory containing the Metanorma document, run this:

[source,sh]
----
docker run -v "$(pwd)":/metanorma/ ribose/metanorma -t {flavor} -x {extensions} {my-document-file}
----

Where,

* `{my-document-file}` is the name of the Metanorma document file, such as `iso-12345.adoc`
* `{flavor}` is the flavor of Metanorma document, such as `iso`
* `{extensions}` is a list of extensions desired, such as `xml,html,doc`

Example (real-life):

[source,sh]
----
docker run -v "$(pwd)":/metanorma ribose/metanorma -t iso -x xml,html,doc iso-tc154-8601-2-en.adoc
----



The above command actually uses a couple assumptions set in the
built container itself, including:

* the `/metanorma` path is set within the container's `WORKDIR`
* the `metanorma` command is set in the container's `ENTRYPOINT`

The full command is actually this:

[source,sh]
----
docker run -v "$(pwd)":/metanorma/ -w /metanorma ribose/metanorma metanorma -t iso -x {extensions} {my-document-file}
----




=== Running the Metamorma container via the Makefile

The `Makefile` makes life much simpler.
To start the `metanorma` container and enter it with `bash`,
all you need is:

[source,sh]
----
make run-metanorma
----

To kill the container:

[source,sh]
----
make kill-metanorma
----

The `Makefile` supports the following commands related to running:

[source,sh]
----
make {run,kill,rm,rmf}-metanorma
----


== Building the containers yourself

=== Container flavors

There are two supported container flavors:

* `metanorma`: official release of the Metanorma container, using released gems
* `mn`: experimental release of the Metanorma container, using unreleased (but hopefully functional) gems


=== Prerequisites

This `Makefile` allows you to build the Metanorma container
yourself.

All you have to set is a couple environment variables.

For example, if you use AWS' ECR, you can set this:

[source,sh]
----
export NS_REMOTE=${account-id}.dkr.ecr.${region}.amazonaws.com/${account-name}
export DOCKER_LOGIN_CMD='aws ecr get-login --no-include-email \
  --region=${region} --registry-ids=${ecr-registry-id}'
----

If you want to build other containers you can add these:

[source,sh]
----
export ITEMS="1 2"
export IMAGE_TYPES="metanorma metanorma-ubuntu-18.04"
export VERSIONS="1.0 1.0"
export ROOT_IMAGES="ubuntu:18.10 ubuntu:18.04"
----

The environment variables are used for:

`NS_REMOTE`:: the namespace for your remote repository
(to separate from builds intended for local consumption)

`DOCKER_LOGIN_CMD`:: how you authenticate against your repository

`ITEMS`:: a sequential number list for iterating `IMAGE_TYPES`,
its numbers are indexes to the content in `IMAGE_TYPES`

`IMAGE_TYPES`:: the different containers you support. Remember
to create a directory for each of these names with a `Dockerfile.in`
within. See existing examples.

`VERSIONS`:: how you want to tag the resulting image

`ROOT_IMAGES`:: the container your new image should be based on


=== Makefile build targets

The `Makefile` supports the following commands for building:

[source,sh]
----
make {build,push,tag,squash,clean-remote,clean-local}-{container-flavor}
----

NOTE: The `squash-{container-flavor}` command relies on
(and automatically pulls) the
https://github.com/riboseinc/docker-squash-container[`docker-squash` container]


=== Updating container flavors

All files relating to building a certain container flavor is located in the
`{container-flavor}` directory.

For the `metanorma` and `mn` flavors, we update using this procedure:

[source,sh]
----
pushd metanorma
bundle update
popd
# Gemfile.lock is updated
----

Then, we build, squash and push the container:

[source,sh]
----
make bsp-metanorma
----

Lastly, we tag and push the built container as latest.

[source,sh]
----
make latest-tp-metanorma
----


== Chain commands

If you feel tired typing out this:

[source,sh]
----
make build-metanorma squash-metanorma push-metanorma
----

We have a list of shortcut targets to save you from repeating fingers.
For example:

[source,sh]
----
# equivalent to make {build,squash,push}-{container-flavor}
make bsp-metanorma
----

The shortcut targets are:

`bsp-{target}`:: build + squash + push
`btp-{target}`:: build + tag + push
`bs-{target}`:: build + squash
`bt-{target}`:: build + tag
`sp-{target}`:: squash + push
`tp-{target}`:: tag + push
