= Metanorma Linux Container (Ubuntu)

== Purpose

Metanorma


== Pulling the container

This container is published at the https://hub.docker.com/r/ribose/metanorma/[Docker Registry] as `docker.io/ribose/metanorma` or `ribose/metanorma`,
and can be pulled with the following command:

[source,sh]
----
docker pull ribose/metanorma
----


== Usage

The `Makefile` in this repository is rather complicated, but
all necessary for enabling quick iteration of the resulting
containers.


=== Running of the `metanorma` container via docker

So running `systemd` from a CentOS container is rather cumbersome
(didn't think that would stop you!).

To make `systemd` work, the container needs to be started with
`--security-opt` and `--cap-add` arguments, which basically give it
`root` access to the host.

If that didn't stop you, here are the instructions:

[source,sh]
----
docker run --rm ribose/metanorma
----

To get inside the container, you must `docker exec` into it.
Remember `systemd` is already running as PID 1 (not `bash`!).


=== Running the containers (and bash) via the Makefile

And the `Makefile` makes life much simpler.
To start the `metanorma` container and enter it with `bash`,
all you need is:

[source,sh]
----
make run-metanorma
----

To kill the container:

[source,sh]
----
make kill-metanorma
----

The `Makefile` supports the following commands related to running:

[source,sh]
----
make {run,kill,rm,rmf}-metanorma
----


== Building the containers yourself

For those concerned about security you might not want to use
our container but build your own.
This `Makefile` allows for such a case (as you can imagine).

All you have to set is a couple environment variables.

For example, if you use AWS' ECR, you can set this:

[source,sh]
----
export NS_REMOTE=${account-id}.dkr.ecr.${region}.amazonaws.com/${account-name}
export DOCKER_LOGIN_CMD='aws ecr get-login --no-include-email \
  --region=${region} --registry-ids=${ecr-registry-id}'
----

If you want to build other containers you can add these:

[source,sh]
----
export ITEMS="1 2"
export IMAGE_TYPES="metanorma metanorma-ubuntu-18.04"
export VERSIONS="1.0 1.0"
export ROOT_IMAGES="ubuntu:18.10 ubuntu:18.04"
----

The environment variables are used for:

`NS_REMOTE`:: the namespace for your remote repository
(to separate from builds intended for local consumption)

`DOCKER_LOGIN_CMD`:: how you authenticate against your repository

`ITEMS`:: a sequential number list for iterating `IMAGE_TYPES`,
its numbers are indexes to the content in `IMAGE_TYPES`

`IMAGE_TYPES`:: the different containers you support. Remember
to create a directory for each of these names with a `Dockerfile.in`
within. See existing examples.

`VERSIONS`:: how you want to tag the resulting image

`ROOT_IMAGES`:: the container your new image should be based on

=== Makefile build targets

The `Makefile` supports the following commands for building:

[source,sh]
----
make {build,push,tag,squash,clean-remote,clean-local}-{container-flavor}
----

NOTE: The `squash-{container-flavor}` command relies on
(and automatically pulls) the
https://github.com/riboseinc/docker-squash-container[`docker-squash` container]


== Chain commands

If you feel tired typing out this:

[source,sh]
----
make build-metanorma squash-metanorma push-metanorma
----

We have a list of shortcut targets to save you from repeating fingers.
For example:

[source,sh]
----
# equivalent to make {build,squash,push}-{container-flavor}
make bsp-metanorma
----

The shortcut targets are:

`bsp-{target}`:: build + squash + push
`btp-{target}`:: build + tag + push
`bs-{target}`:: build + squash
`bt-{target}`:: build + tag
`sp-{target}`:: squash + push
`tp-{target}`:: tag + push
