source "https://rubygems.org"

gem "metanorma"
gem "metanorma-cli"
gem "metanorma-csd", git: "https://github.com/riboseinc/metanorma-csd"
gem "metanorma-nist", git: "https://github.com/riboseinc/metanorma-nist"
