FROM ${ROOT_IMAGE}

MAINTAINER Open Source at Ribose <open.source@ribose.com>

# install dependencies
RUN apt-get update && apt-get install -y curl gnupg2
RUN curl -sSL https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | bash -s

# install metanorma toolchain
RUN mkdir -p /setup
COPY ${METANORMA_IMAGE_NAME}/Gemfile /setup/Gemfile
RUN cd /setup && bundle install

# export java executable path
ENV JAVA_HOME /usr/lib/jvm/default-java
ENV PATH $PATH:$JAVA_HOME/bin

# cleanup and set base entrypoint
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /metanorma
CMD ["metanorma"]
