FROM ${ROOT_IMAGE}

MAINTAINER Open Source at Ribose <open.source@ribose.com>

# install dependencies
RUN apt-get update && apt-get install -y curl gnupg2 software-properties-common
RUN curl -sSL https://github.com/mikefarah/yq/releases/download/2.4.0/yq_linux_amd64 -o /usr/bin/yq && chmod +x /usr/bin/yq
RUN curl -sSL https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | bash -s

# install latest bundler
RUN gem install bundler

# install metanorma toolchain
RUN mkdir -p /setup
COPY ${METANORMA_IMAGE_NAME}/Gemfile /setup/Gemfile
RUN cd /setup && bundle install

# export java executable path
ENV JAVA_HOME /usr/lib/jvm/default-java
ENV PATH $PATH:$JAVA_HOME/bin
ENV RUBYOPT -rbundler/setup
ENV BUNDLE_GEMFILE /setup/Gemfile

# cleanup and set base entrypoint
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /metanorma
CMD ["metanorma"]
