name: docker-mn

on:
  push:
    branches: [ master ]
    tags:
    - '*'
  pull_request:
    branches:
    - '**'
  repository_dispatch:
  workflow_dispatch:

jobs:
  build-debian:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
    - uses: actions/checkout@v2

    - name: Prepare Docker Environment
      shell: bash
      run: |
        echo '{"cgroup-parent": "/actions_job", "experimental": true, "features": { "buildkit": true }}' | sudo tee /etc/docker/daemon.json 2>/dev/null
        sudo service docker restart

    - uses: metanorma/metanorma-build-scripts/gh-rubygems-setup-action@main
      with:
        token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

    - name: Build container
      id: build
      run: |
        make build-mn
        echo "::set-output name=container_name::$(make print-local-name-mn)"

    - uses: yuichielectric/dive-action@0.0.4
      with:
        image: ${{ steps.build.outputs.container_name }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests
      env:
        GITHUB_CREDENTIALS: "metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}"
      run: |
        make test-mn

    - name: Tag and push container latest
      if: github.ref == 'refs/heads/master'
      env:
        DOCKER_LOGIN_USERNAME: ${{ secrets.DOCKER_LOGIN_USERNAME }}
        DOCKER_LOGIN_PASSWORD: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
      run: |
        make tag-mn latest-tp-mn

    - name: Tag and push container versioned
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        DOCKER_LOGIN_USERNAME: ${{ secrets.DOCKER_LOGIN_USERNAME }}
        DOCKER_LOGIN_PASSWORD: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
      run: |
        make tp-mn latest-tp-mn

    - name: Trigger samples repositories
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        GH_USERNAME: metanorma-ci
        GH_ACCESS_TOKEN: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
      run: |
        curl -LO --retry 3 https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/main/trigger-gh-actions.sh
        for repo in iso cc gb iec itu ogc un iho nist
        do
          sh trigger-gh-actions.sh $ORGANISATION mn-samples-$repo $GH_USERNAME $GH_ACCESS_TOKEN $GITHUB_REPOSITORY
        done

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Prepare Docker Environment
      shell: bash
      run: |
        echo '{"cgroup-parent": "/actions_job", "experimental": true, "features": { "buildkit": true }}' | sudo tee /etc/docker/daemon.json 2>/dev/null
        sudo service docker restart

    - uses: metanorma/metanorma-build-scripts/gh-rubygems-setup-action@main
      with:
        token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

    - name: Build container
      id: build
      run: |
        make build-mn-ubuntu
        echo "::set-output name=container_name::$(make print-local-name-mn-ubuntu)"

    - uses: yuichielectric/dive-action@0.0.4
      with:
        image: ${{ steps.build.outputs.container_name }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests
      env:
        GITHUB_CREDENTIALS: "metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}"
      run: |
        make test-mn-ubuntu

    - name: Tag and push container latest
      if: github.ref == 'refs/heads/master'
      env:
        DOCKER_LOGIN_USERNAME: ${{ secrets.DOCKER_LOGIN_USERNAME }}
        DOCKER_LOGIN_PASSWORD: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
      run: |
        make tag-mn-ubuntu latest-tp-mn-ubuntu

    - name: Tag and push container versioned
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        DOCKER_LOGIN_USERNAME: ${{ secrets.DOCKER_LOGIN_USERNAME }}
        DOCKER_LOGIN_PASSWORD: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
      run: |
        make tp-mn-ubuntu