name: Docker Security Scan with Dockle

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile.*'
      - '.dockle.toml'
      - '.github/workflows/dockle.yml'
  pull_request:
    paths:
      - 'Dockerfile.*'
      - '.dockle.toml'
      - '.github/workflows/dockle.yml'
  workflow_dispatch:

jobs:
  dockle-scan:
    name: Scan Docker images with Dockle
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-type: [alpine, ruby, ubuntu]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.${{ matrix.image-type }}
          tags: metanorma-${{ matrix.image-type }}:test
          load: true
          push: false
          build-args: |
            METANORMA_IMAGE_NAME=metanorma-${{ matrix.image-type }}

      - name: Run Dockle
        uses: erzz/dockle-action@v1
        continue-on-error: true
        with:
          image: metanorma-${{ matrix.image-type }}:test
          failure-threshold: fatal
          report-format: sarif
          exit-code: 0

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: dockle-${{ matrix.image-type }}.sarif
          category: dockle-${{ matrix.image-type }}
