name: docker-mn

on:
  push:
    branch: master
    tags:
    - '*'
  pull_request:
    branches:
    - '**'
  repository_dispatch:

jobs:
  build-debian:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build container
      run: |
        make build-mn

    - name: Run tests
      run: |
        make test-mn

    - name: Squash and push container
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
      env:
        DOCKER_LOGIN_USERNAME: ${{ secrets.DOCKER_LOGIN_USERNAME }}
        DOCKER_LOGIN_PASSWORD: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
      run: |
        make bsp-mn latest-tp-mn

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build container
      run: |
        make build-mn-ubuntu

    - name: Run tests
      run: |
        make test-mn-ubuntu

    - name: Squash and push container
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
      env:
        DOCKER_LOGIN_USERNAME: ${{ secrets.DOCKER_LOGIN_USERNAME }}
        DOCKER_LOGIN_PASSWORD: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
      run: |
        make bsp-mn-ubuntu latest-tp-mn-ubuntu
