name: Docker Lint with Hadolint

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile.*'
      - '.hadolint.yaml'
      - '.github/workflows/hadolint.yml'
  pull_request:
    paths:
      - 'Dockerfile.*'
      - '.hadolint.yaml'
      - '.github/workflows/hadolint.yml'
  workflow_dispatch:

jobs:
  hadolint:
    name: Lint Dockerfiles with Hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.alpine
          config: .hadolint.yaml
          format: sarif
          output-file: hadolint-alpine.sarif
          no-fail: true

      - name: Run Hadolint (Ruby)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.ruby
          config: .hadolint.yaml
          format: sarif
          output-file: hadolint-ruby.sarif
          no-fail: true

      - name: Run Hadolint (Ubuntu)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.ubuntu
          config: .hadolint.yaml
          format: sarif
          output-file: hadolint-ubuntu.sarif
          no-fail: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: hadolint-*.sarif
          category: hadolint
