name: Docker Lint with Hadolint

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile.*'
      - '.hadolint.yaml'
      - '.github/workflows/hadolint.yml'
  pull_request:
    paths:
      - 'Dockerfile.*'
      - '.hadolint.yaml'
      - '.github/workflows/hadolint.yml'
  workflow_dispatch:

permissions:
 contents: read
 security-events: write

jobs:
  hadolint:
    name: Hadolint (${{ matrix.image_type }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_type: [alpine, ruby, ubuntu]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.${{ matrix.image_type }}
          config: .hadolint.yaml
          format: sarif
          output-file: hadolint-${{ matrix.image_type }}.sarif
          no-fail: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: hadolint-${{ matrix.image_type }}.sarif
          category: hadolint-${{ matrix.image_type }}
