name: Container Vulnerability Scan with Trivy

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile.*'
      - '.github/workflows/trivy.yml'
  pull_request:
    paths:
      - 'Dockerfile.*'
      - '.github/workflows/trivy.yml'
  workflow_dispatch:

permissions:
 contents: read
 security-events: write

jobs:
  trivy-scan:
    name: Trivy image scan (${{ matrix.image_type }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_type: [alpine, ruby, ubuntu]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.${{ matrix.image_type }}
          tags: metanorma-${{ matrix.image_type }}:test
          load: true
          push: false
          build-args: |
            METANORMA_IMAGE_NAME=metanorma-${{ matrix.image_type }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: metanorma-${{ matrix.image_type }}:test
          format: 'sarif'
          output: 'trivy-${{ matrix.image_type }}.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'  # Don't fail the build for now

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-${{ matrix.image_type }}.sarif
          category: trivy-${{ matrix.image_type }}
